table 'Product Subcategories Lookup'
	lineageTag: 3f47b527-fe3c-45b1-bd89-fb084bfdc6d2

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 781ede22-a8c2-4229-bc39-72a409d7f7fa
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column SubcategoryName
		dataType: string
		lineageTag: 788ee164-07bc-4e91-8db0-5c2fc846a211
		summarizeBy: none
		sourceColumn: SubcategoryName

		annotation SummarizationSetBy = Automatic

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 6e49095f-3572-45ee-8f5b-aa2705fd4ab8
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	partition 'Product Subcategories Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\PORTFOLIO\POWER BI\Sports Product Tracker\dataset\AdventureWorks Product Subcategories Lookup.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductSubcategoryKey", Int64.Type}, {"SubcategoryName", type text}, {"ProductCategoryKey", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

